version: '{build}'
image: Visual Studio 2019
stack: python 3.10
skip_branch_with_pr: true
init:
- cmd: set PATH=C:\Python310;C:\Python310\Scripts;%PATH%
install:
- ps: python -m pip install -r requirements.txt
build: false
test_script:
- ps: python wsgi.py
